# Generated by Django 5.2.5 on 2025-08-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllInOneAccessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aioa_icon_type', models.CharField(choices=[('aioa-icon-type-1', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-1.svg'), ('aioa-icon-type-2', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-2.svg'), ('aioa-icon-type-3', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-3.svg'), ('aioa-icon-type-4', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-4.svg'), ('aioa-icon-type-5', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-5.svg'), ('aioa-icon-type-6', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-6.svg'), ('aioa-icon-type-7', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-7.svg'), ('aioa-icon-type-8', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-8.svg'), ('aioa-icon-type-9', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-9.svg'), ('aioa-icon-type-10', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-10.svg'), ('aioa-icon-type-11', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-11.svg'), ('aioa-icon-type-12', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-12.svg'), ('aioa-icon-type-13', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-13.svg'), ('aioa-icon-type-14', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-14.svg'), ('aioa-icon-type-15', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-15.svg'), ('aioa-icon-type-16', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-16.svg'), ('aioa-icon-type-17', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-17.svg'), ('aioa-icon-type-18', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-18.svg'), ('aioa-icon-type-19', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-19.svg'), ('aioa-icon-type-20', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-20.svg'), ('aioa-icon-type-21', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-21.svg'), ('aioa-icon-type-22', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-22.svg'), ('aioa-icon-type-23', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-23.svg'), ('aioa-icon-type-24', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-24.svg'), ('aioa-icon-type-25', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-25.svg'), ('aioa-icon-type-26', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-26.svg'), ('aioa-icon-type-27', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-27.svg'), ('aioa-icon-type-28', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-28.svg'), ('aioa-icon-type-29', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-29.svg')], default='aioa-icon-type-1', max_length=50, verbose_name='Icon Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomAccessibilitySettings',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wagtail_all_in_one_accessibility.allinoneaccessibility',),
        ),
    ]
