# Generated by Django 4.2.2 on 2023-06-12 10:04

from django.db import migrations, models
import wagtail_all_in_one_accessibility.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wagtail_all_in_one_accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aioa_license_Key', models.CharField(blank=True, default=' ', help_text="<span class='validate_pro'><p>You are currently using Free version which have limited features. </br>Please <a href='https://www.skynettechnologies.com/add-ons/product/all-in-one-accessibility/'>purchase</a> License Key for additional features on the ADA Widget</p></span><script>if(document.querySelector('#id_aioa_license_Key').value != ''){document.querySelector('.validate_pro').style.display='none';} else {document.querySelector('.validate_pro').style.display='block';}</script>", max_length=150, validators=[wagtail_all_in_one_accessibility.models.validate_token], verbose_name='License Key')),
                ('aioa_color_code', models.CharField(blank=True, default=' ', help_text='You can cutomize the ADA Widget color. For example: #FF5733', max_length=50, verbose_name='Hex color code')),
                ('aioa_place', models.CharField(blank=True, choices=[('top_left', 'Top left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('middel_left', 'Middle left'), ('middel_right', 'Middle Right'), ('bottom_left', 'Bottom left'), ('bottom_center', 'Bottom Center'), ('bottom_right', 'Bottom Right')], default=('bottom_right', 'Bottom Right'), max_length=100, verbose_name='Where would you like to place the accessibility icon on your site')),
            ],
            options={
                'verbose_name': 'All in One Accessibility Settings',
                'verbose_name_plural': 'All in One Accessibility Settings',
            },
        ),
    ]
