# Generated by Django 5.2.5 on 2025-08-13 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_all_in_one_accessibility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_color_code',
            field=models.CharField(blank=True, default='', help_text='You can customize the ADA Widget color. For example: #FF5733', max_length=50, verbose_name='Hex Color Code'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_icon_size',
            field=models.CharField(choices=[('aioa-big-icon', ''), ('aioa-medium-icon', ''), ('aioa-default-icon', ''), ('aioa-small-icon', ''), ('aioa-extra-small-icon', '')], default='aioa-default-icon', help_text='This size preview will change according to the selected icon type.', max_length=50, verbose_name='Icon Size'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_place',
            field=models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('middle_left', 'Middle Left'), ('middle_center', 'Middle Center'), ('middle_right', 'Middle Right'), ('bottom_left', 'Bottom Left'), ('bottom_right', 'Bottom Right')], default='bottom_right', max_length=100, verbose_name='Where would you like to place the accessibility icon on your site'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_size',
            field=models.CharField(choices=[('regular', 'Regular Size'), ('oversize', 'Oversize')], default='oversize', max_length=20, verbose_name='Select Widget Size'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='aioa_size_value',
            field=models.PositiveSmallIntegerField(default=50, help_text='20 - 150px are permitted values', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(150)], verbose_name='Select exact icon size (PX)'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='enable_icon_custom_size',
            field=models.BooleanField(default=False, verbose_name='Enable Icon Custom Size'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='enable_widget_icon_position',
            field=models.BooleanField(default=False, verbose_name='Enable Precise accessibility widget icon position'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_bottom',
            field=models.CharField(choices=[('to_the_bottom', 'Top the bottom'), ('to_the_top', 'To the top')], default='to_the_bottom', verbose_name='To the bottom'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_bottom_px',
            field=models.PositiveSmallIntegerField(default=20, help_text='0 - 250px are permitted values', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Bottom offset (PX)'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_right',
            field=models.CharField(choices=[('to_the_left', 'To the left'), ('to_the_right', 'To the right')], default='to_the_left', verbose_name='To the left'),
        ),
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='to_the_right_px',
            field=models.PositiveSmallIntegerField(default=20, help_text='0 - 250px are permitted values', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Right offset (PX)'),
        ),
    ]
