# Generated by Django 5.2.5 on 2025-08-14 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_all_in_one_accessibility', '0002_allinoneaccessibility_aioa_color_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAccessibilitySettings',
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_icon_size',
            field=models.CharField(choices=[('aioa-big-icon', ''), ('aioa-medium-icon', ''), ('aioa-default-icon', ''), ('aioa-small-icon', ''), ('aioa-extra-small-icon', '')], default='aioa-default-icon', help_text='This size preview will change according to the selected icon type.', max_length=50, verbose_name='Select icon size for Desktop'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_icon_type',
            field=models.CharField(choices=[('aioa-icon-type-1', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-1.svg'), ('aioa-icon-type-2', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-2.svg'), ('aioa-icon-type-3', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-3.svg'), ('aioa-icon-type-4', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-4.svg'), ('aioa-icon-type-5', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-5.svg'), ('aioa-icon-type-6', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-6.svg'), ('aioa-icon-type-7', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-7.svg'), ('aioa-icon-type-8', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-8.svg'), ('aioa-icon-type-9', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-9.svg'), ('aioa-icon-type-10', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-10.svg'), ('aioa-icon-type-11', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-11.svg'), ('aioa-icon-type-12', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-12.svg'), ('aioa-icon-type-13', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-13.svg'), ('aioa-icon-type-14', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-14.svg'), ('aioa-icon-type-15', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-15.svg'), ('aioa-icon-type-16', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-16.svg'), ('aioa-icon-type-17', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-17.svg'), ('aioa-icon-type-18', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-18.svg'), ('aioa-icon-type-19', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-19.svg'), ('aioa-icon-type-20', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-20.svg'), ('aioa-icon-type-21', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-21.svg'), ('aioa-icon-type-22', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-22.svg'), ('aioa-icon-type-23', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-23.svg'), ('aioa-icon-type-24', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-24.svg'), ('aioa-icon-type-25', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-25.svg'), ('aioa-icon-type-26', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-26.svg'), ('aioa-icon-type-27', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-27.svg'), ('aioa-icon-type-28', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-28.svg'), ('aioa-icon-type-29', 'https://www.skynettechnologies.com/sites/default/files/aioa-icon-type-29.svg')], default='aioa-icon-type-1', max_length=50, verbose_name='Select icon type'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_bottom_px',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Bottom offset (PX)'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_right_px',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(250)], verbose_name='Right offset (PX)'),
        ),
    ]
