# Generated by Django 5.2.5 on 2025-08-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_all_in_one_accessibility', '0003_delete_customaccessibilitysettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allinoneaccessibility',
            name='domain_url',
            field=models.URLField(blank=True, help_text='Auto-filled from browser when saving settings.', verbose_name='Domain URL (auto-filled)'),
        ),
    ]
