# Generated by Django 5.2.5 on 2025-08-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_all_in_one_accessibility', '0004_allinoneaccessibility_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_bottom',
            field=models.CharField(choices=[('to_the_bottom', 'Top the bottom'), ('to_the_top', 'To the top')], default='to_the_bottom', max_length=50, verbose_name='To the bottom'),
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_right',
            field=models.CharField(choices=[('to_the_left', 'To the left'), ('to_the_right', 'To the right')], default='to_the_left', max_length=50, verbose_name='To the left'),
        ),
    ]
