# Generated by Django 5.2.5 on 2025-08-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_all_in_one_accessibility', '0005_alter_allinoneaccessibility_to_the_bottom_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allinoneaccessibility',
            options={'verbose_name': 'All In One Accessibility', 'verbose_name_plural': 'All In One Accessibility'},
        ),
    ]
