# Generated by Django 5.2.5 on 2025-12-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_all_in_one_accessibility', '0006_alter_allinoneaccessibility_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='aioa_place',
            field=models.CharField(choices=[('top_left', 'Top Left'), ('top_center', 'Top Center'), ('top_right', 'Top Right'), ('middle_left', 'Middle Left'), ('middle_right', 'Middle Right'), ('bottom_left', 'Bottom Left'), ('bottom_center', 'Bottom Center'), ('bottom_right', 'Bottom Right')], default='bottom_right', max_length=100, verbose_name='Where would you like to place the accessibility icon on your site'),
        ),
    ]
