# Generated by Django 5.2.5 on 2025-12-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_all_in_one_accessibility', '0007_alter_allinoneaccessibility_aioa_place'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allinoneaccessibility',
            options={'verbose_name': 'All in One Accessibility', 'verbose_name_plural': 'All in One Accessibility'},
        ),
        migrations.AlterField(
            model_name='allinoneaccessibility',
            name='to_the_bottom',
            field=models.CharField(choices=[('to_the_bottom', 'To the bottom'), ('to_the_top', 'To the top')], default='to_the_bottom', max_length=50, verbose_name='To the bottom'),
        ),
    ]
